# fly.toml app configuration file generated for ephemeral-pricing-oracle-pyth-lazer-tap-trading on 2025-04-14T16:11:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ephemeral-pricing-oracle-pyth-lazer-tap-trading'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 8
